#!/bin/bash

function usage()
{
	echo -e "login\tIt is used to login in the IceScrum account and create the cookies"
  exit 0
}

while getopts ":" command
do
	case "${command}" in
		\?)
			usage
			;;
	esac
done

curl -c /tmp/cookie.jar ${ICESCRUM_URL}/j_spring_security_check -d "j_username=${ICESCRUM_USER}&j_password=${ICESCRUM_PASSWD}" -X POST
