#!/bin/bash

function usage()
{
  exit 0
}

while getopts ":" command
do
	case "${command}" in
		\?)
			usage
			;;
	esac
done

LOGGED=`find /tmp/cookie.jar -mmin -45 2>/dev/null | wc -l`

if [ $LOGGED -ne 1 ]
then
  curl -c /tmp/cookie.jar ${ICESCRUM_URL}/j_spring_security_check -d "j_username=${ICESCRUM_USER}&j_password=${ICESCRUM_PASSWD}" -X POST
fi
