#!/bin/bash

function usage()
{
	echo -e "task"
	echo -e "\t-l\tList all tasks"
	echo -e "\t-s <ID>\tShow the relevant data"
	echo -e "\t-S <ID>\tShow the relevant data in one line"
  echo -e "\tnew <STORYID> <BACKLOGID> <HOURS> <TITLE>"
  echo -e "\tworking <ID>"
  echo -e "\tchangeTime <ID> <HRS>"
  exit 0
}

icescrum login

if [ "$1" == "working" ]
then
  TID=$2
  HRS=$3
  curl -s -b /tmp/cookie.jar -c /tmp/cookie.jar "${ICESCRUM_URL}/task/state" -H "Referer: ${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_NAME}" -H "X-Requested-With: XMLHttpRequest" --data "product=${ICESCRUM_PROJECT_ID}&id=${TID}&task.state=1"
elif [ "$1" == "changeTime" ]
then
  TID=$2
  HRS=$3
  curl -s -b /tmp/cookie.jar -c /tmp/cookie.jar "${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_ID}/task/update/$TID" -H "Referer: ${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_NAME}" -H "X-Requested-With: XMLHttpRequest" --data "task.estimation=$HRS"
elif [ "$1" == "new" ]
then
  SID=$2
  BID=$3
  HRS=$4
  shift 4
  curl -s -b /tmp/cookie.jar -c /tmp/cookie.jar "${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_ID}/task/save" -H "Referer: ${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_NAME}" -H "X-Requested-With: XMLHttpRequest" --data "task.parentStory.id=$SID&task.sprint.id=$BID&task.estimation=$HRS&task.name=$*"
else
  while getopts ":ls:S:" command
  do
    case "${command}" in
      l)
        curl -s -b /tmp/cookie.jar -c /tmp/cookie.jar "${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_ID}/task/list" -H "Referer: ${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_NAME}" -H "X-Requested-With: XMLHttpRequest" --get -H "Content-Type: application/json" | ${ICESCRUM_CLI_HOME}/renders/tasks-list.py $*
        ;;
      S)
        TASK_ID=${OPTARG}
        curl -s -b /tmp/cookie.jar -c /tmp/cookie.jar "${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_ID}/task/${TASK_ID}" -H "Referer: ${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_NAME}" -H "X-Requested-With: XMLHttpRequest" --get -H "Content-Type: application/json" | ${ICESCRUM_CLI_HOME}/renders/tasks-show-oneline.py
        shift
        OPTIND=1
        ;;
      s)
        TASK_ID=${OPTARG}
        curl -s -b /tmp/cookie.jar -c /tmp/cookie.jar "${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_ID}/task/${TASK_ID}" -H "Referer: ${ICESCRUM_URL}/p/${ICESCRUM_PROJECT_NAME}" -H "X-Requested-With: XMLHttpRequest" --get -H "Content-Type: application/json" | ${ICESCRUM_CLI_HOME}/renders/tasks-show.py
        shift
        OPTIND=1
        ;;
      \?)
        usage
        ;;
    esac
  done
fi
